"""Command phase: live unit state and command points.

Autogenerated then hand-corrected: the generated version added NOT NULL columns
with no server_default, which fails on any table that already holds rows. The
defaults below are what make this safe to run against a live database.

Revision ID: 0002_command_phase
Revises: 0001_baseline
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = "0002_command_phase"
down_revision: Union[str, None] = "0001_baseline"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("game_players", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("command_points", sa.Integer(), nullable=False, server_default="0")
        )

    with op.batch_alter_table("game_units", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("models_lost", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("wounds_lost", sa.Integer(), nullable=False, server_default="0")
        )
        batch_op.add_column(
            sa.Column("is_battle_shocked", sa.Boolean(), nullable=False, server_default="0")
        )
        # Null means "never tested"; no default needed.
        batch_op.add_column(sa.Column("shock_tested_round", sa.Integer(), nullable=True))


def downgrade() -> None:
    with op.batch_alter_table("game_units", schema=None) as batch_op:
        batch_op.drop_column("shock_tested_round")
        batch_op.drop_column("is_battle_shocked")
        batch_op.drop_column("wounds_lost")
        batch_op.drop_column("models_lost")

    with op.batch_alter_table("game_players", schema=None) as batch_op:
        batch_op.drop_column("command_points")
